### ISSUE TITLE
Crash in the collaboration gateway script of the Scoring v2.0.1 container 

### ISSUE THREAD

**Issue by ssinghxyz** [SpectrumCollaborationChallenge/phase2-hurdle#11]
Hello,
The collaboration gateway of scoring v2.0.1 container crashes after peering with a competitor container's collaboration gateway. The crash happens when the scoring container's gateway tries to send network usage, in the function "send_network_usageI()". 
The crash log is : 
_2018-02-14 00:47:46,635 ERROR 

/usr/local/lib/python2.7/dist-packages/sc2_remapper-0.1.0-py2.7.egg/EGG-INFO/scripts/collab_client - 1087 - <module> - main()

2018-02-14 00:47:46,635 ERROR 

/usr/local/lib/python2.7/dist-packages/sc2_remapper-0.1.0-py2.7.egg/EGG-INFO/scripts/collab_client - 1067 - main - collab_client.run_as_daemon()

2018-02-14 00:47:46,635 ERROR 

/usr/local/lib/python2.7/dist-packages/sc2_remapper-0.1.0-py2.7.egg/EGG-INFO/scripts/collab_client - 1042 - run_as_daemon - self.run()

2018-02-14 00:47:46,635 ERROR 

/usr/local/lib/python2.7/dist-packages/sc2_remapper-0.1.0-py2.7.egg/EGG-INFO/scripts/collab_client - 984 - run - self.send_network_usage(peer)

2018-02-14 00:47:46,635 ERROR 

/usr/local/lib/python2.7/dist-packages/sc2_remapper-0.1.0-py2.7.egg/EGG-INFO/scripts/collab_client - 826 - send_network_usage - network_usage = message.informational_declaration.network_level_resource_usage.add()

2018-02-14 00:47:46,635 ERROR 

Unhandled exception!
<type 'exceptions.AttributeError'>
'InformationalDeclaration' object has no attribute 'network_level_resource_usage'
<traceback object at 0x7f3f5b445050>
line number = 5
frame = <frame object at 0x7f3f71eea050>

None_

**Comment by craig-pomeroy** [comment]
Thanks for the bug report. That clearly shouldn't be happening. We'll dig in to what is going on and get back to you.

**Comment by craig-pomeroy** [comment]
This issue is fixed as of 5db9c16a09991a41c5cce9be0655bb024f241ad5
