### ISSUE TITLE
Nominal throughput regarding on the documentation

### ISSUE THREAD

**Issue by bfzhou** [SpectrumCollaborationChallenge/phase2-hurdle#12]
Hi there, 

I am new to this hurdle and I am trying to get familiar with the whole system but I am having trouble finding the defined metrics for the hurdle in any configuration files.  In the Hurdle Problem Description it mentioned: 

> Entrance Hurdle Completion Criteria: Successful completion of the Entrance Hurdle is defined as both networks achieving 85% of the Bot Network’s nominal throughput. 

However, I am not able to find this nominal value defined in neither the source code nor the bot images. Could anyone help me with this?

Thanks in advance,
Baofeng

**Comment by FarshadKoohifar** [comment]
Is there any new information on this?

Farsahd

**Comment by craig-pomeroy** [comment]
We'll accept a packet success rate of 85% or higher for both the bot network and the competitor network when running the hurdle using the command in the "Running the Hurdle Script in Scoring Mode" section of 
https://github.com/SpectrumCollaborationChallenge/phase2-hurdle/blob/master/doc/Phase-2-Hurdle-Instructions-and-Logistics.md
