### ISSUE TITLE
Enabling debug output in envsim prevents bots from transmitting packets

### ISSUE THREAD

**Issue by karumugam3** [SpectrumCollaborationChallenge/phase2-hurdle#14]
When --enable-debug-output is used while running the hurdle, the bots transfer 0 packets. The same bots without "--enable-debug-output" function well. Is this a bug or am I missing something? Any help is appreciated. Thanks.

**Comment by craig-pomeroy** [comment]
There are a couple of reasons this might not work: 
1) If you are not viewing the output generated by "enable-debug-output" with a viewer, eventually the gnuradio block responsible for sending those debug samples over the network is going to stop, blocking the rest of the environment simulator from processing samples.

2) This does take more CPU power to run. If you were just barely keeping up before, running in debug mode will make you fall behind. 

Are you running with a viewer, such as the envsim_viewer included in gr-envsim/apps, when you use debug mode?

**Comment by karumugam3** [comment]
Yes, I'm using the envsim_viewer.grc included in the release. 

I don't get any errors, it just shows no signals.

**Comment by craig-pomeroy** [comment]
That sounds like you may not be using the correct IP address or port in your command line. Can you confirm that you are using the IP address associated with your instance of the phase2Hurdle container's eth0 interface when you are running the envsim viewer?

**Comment by karumugam3** [comment]
My bad. I was not using the correct IP address. Thanks for the help. By the way, all three scoring bots still all have col0 interface.
