### ISSUE TITLE
Container with col0 interface

### ISSUE THREAD

**Issue by karumugam3** [SpectrumCollaborationChallenge/phase2-hurdle#15]
The current release of the hurdle container instantiates 3 copies of the container each with tr0, col0, and usrp0 interfaces. The documentation says that only one SRN will have the col0 interface. Will you be issuing another edited release or will all 3 competitor containers have col0 interface?

Any help is appreciated. Thanks!

**Comment by craig-pomeroy** [comment]
This commit is fixed as of 3dcb4d53ea513745497d0811a3867710536b93f7. I'm building new images now. There are no changes to the practice, scoring, or container base images, only to the phase2Hurdle container.

**Comment by craig-pomeroy** [comment]
fixed as of v2-1-2
