### ISSUE TITLE
dummy image missing files

### ISSUE THREAD

**Issue by dpavsrtrl** [SpectrumCollaborationChallenge/phase2-hurdle#4]
ran the hurdle script `cd /root/phase2-hurdle/hurdle_execution
./run_hurdle.py --duration=60 --image-file=dummy-image.tar.gz --clean-competitor-containers`

[Here's the output](https://gist.github.com/dpavsrtrl/7b77be77a7d3dc688bce7690b118a71b)

I believe dummy-image is missing some required files, most notably /root/radio_api

here's the [listing of dummy-image.tar.gz ](https://gist.github.com/dpavsrtrl/8affe333ba9bd993d33e704d88248527)

**Comment by craig-pomeroy** [comment]
Hi, 

That's not an accidental omission. The dummy image exists only so that the hurdle script doesn't crash when following the instructions for getting started with the Hurdle. It has nothing in /root/radio_api/, it does not connect to the RF environment, and it cannot send or receive traffic.  

You are right in that a working container would have all of these things.

**Comment by dpavsrtrl** [comment]
[Instructions and Logistics](https://github.com/SpectrumCollaborationChallenge/phase2-hurdle/blob/master/doc/Phase-2-Hurdle-Instructions-and-Logistics.md) led me to believe I would get some traffic with dummy image. Maybe that's the issue.

**Comment by craig-pomeroy** [comment]
You should see something like this at the end of that script: 

traffic_scoring INFO: Bot network transfered a total of 1504 packets out of 1560
traffic_scoring INFO: Competitor network transfered a total of 0 packets out of 1560

The bot network should be able to send traffic. The competitor network, which in this case is based on the dummy image, will not.

Are the bots getting traffic through for you?

**Comment by dpavsrtrl** [comment]
The output I linked in the first comment is full output, followed by me pasting *.drc and *.mgn files. It doesn't not show any statistics.

**Comment by craig-pomeroy** [comment]
I think I see at least part of the issue. I'll have to cut a new release based on the latest commit. I'll get that in over the weekend. I'll keep this issue open until you get a chance to test with the updated containers in the next release.

**Comment by dpavsrtrl** [comment]
Looking forward to the new release :)

**Comment by bepepa** [comment]
Has this issue been fixed? I'm still observing pretty much the exact same output as dpvsrtrl. The only difference I see in the respective outputs is the absence of `error: The container is currently running, stop it first or pass --force.` (line 854 in the output posted with the first message).

I'm definitely not getting traffic reports and traffic log files are empty.

**Comment by craig-pomeroy** [comment]
Version 2.0.0 includes updates to the bots, competitor base container, and hurdle container that mitigate the problems noted in this Issue. The dummy image is a blank Ubuntu image and will not include any hurdle specific files. However, the competitor image provided along with the release does include some default files in /root/radio_api if you want to see more of the Hurdle command and control scripts running without throwing errors. If you are still running into problems, please feel free to reopen this issue.
