### ISSUE TITLE
The line containing "traffic_scoring INFO" is not apearing in the run_hurdle.py log.

### ISSUE THREAD

**Issue by FarshadKoohifar** [SpectrumCollaborationChallenge/phase2-hurdle#5]
Hi, 
We are supposed to get these two lines when run_hurdle.py finishes:
`traffic_scoring INFO: Bot network transfered a total of 1504 packets out of 1560
traffic_scoring INFO: Competitor network transfered a total of 0 packets out of 1560`

But I do not get those lines at all. Here is the end of my log:
`calling /root/radio_api/status.sh on competitor-hurdle-srn5
return code: 255
stdout: 
stderr: 
calling /root/radio_api/status.sh on competitor-hurdle-srn6
return code: 255
stdout: 
stderr: 
Stopping traffic by running ./traffic_control.py stop
stopping MGEN flows and services
Stopping MGEN service
running on tgen1: systemctl stop mgen
Stopping MGEN service
running on tgen2: systemctl stop mgen
Stopping MGEN service
running on tgen3: systemctl stop mgen
Stopping MGEN service
running on tgen4: systemctl stop mgen
Stopping MGEN service
running on tgen5: systemctl stop mgen
Stopping MGEN service
running on tgen6: systemctl stop mgen

Tearing down routing by running ./traffic_routing_teardown.sh
The current routing table is:
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.227.33.1     0.0.0.0         UG    0      0        0 eth0
10.227.33.0     *               255.255.255.0   U     0      0        0 eth0
172.16.0.0      *               255.255.0.0     U     0      0        0 canbr0
172.30.101.0    *               255.255.255.0   U     0      0        0 colbr0
192.168.40.0    *               255.255.255.0   U     0      0        0 usrpbr0
192.168.101.0   192.168.101.1   255.255.255.0   UG    0      0        0 trbr1
192.168.101.0   *               255.255.255.0   U     0      0        0 trbr1
192.168.102.0   192.168.102.1   255.255.255.0   UG    0      0        0 trbr2
192.168.102.0   *               255.255.255.0   U     0      0        0 trbr2
192.168.103.0   192.168.103.1   255.255.255.0   UG    0      0        0 trbr3
192.168.103.0   *               255.255.255.0   U     0      0        0 trbr3
192.168.104.0   192.168.104.1   255.255.255.0   UG    0      0        0 trbr4
192.168.104.0   *               255.255.255.0   U     0      0        0 trbr4
192.168.105.0   192.168.105.1   255.255.255.0   UG    0      0        0 trbr5
192.168.105.0   *               255.255.255.0   U     0      0        0 trbr5
192.168.106.0   192.168.106.1   255.255.255.0   UG    0      0        0 trbr6
192.168.106.0   *               255.255.255.0   U     0      0        0 trbr6

Now removing static routes for each of 6 traffic generators
Removing route 1 of 6 for subnet 192.168.101.0/24 to gateway 192.168.101.1
Removal of route 1 of 6 succeeded
Removing route 2 of 6 for subnet 192.168.102.0/24 to gateway 192.168.102.1
Removal of route 2 of 6 succeeded
Removing route 3 of 6 for subnet 192.168.103.0/24 to gateway 192.168.103.1
Removal of route 3 of 6 succeeded
Removing route 4 of 6 for subnet 192.168.104.0/24 to gateway 192.168.104.1
Removal of route 4 of 6 succeeded
Removing route 5 of 6 for subnet 192.168.105.0/24 to gateway 192.168.105.1
Removal of route 5 of 6 succeeded
Removing route 6 of 6 for subnet 192.168.106.0/24 to gateway 192.168.106.1
Removal of route 6 of 6 succeeded
Traffic generation static routes are now removed. New Routing table:
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.227.33.1     0.0.0.0         UG    0      0        0 eth0
10.227.33.0     *               255.255.255.0   U     0      0        0 eth0
172.16.0.0      *               255.255.0.0     U     0      0        0 canbr0
172.30.101.0    *               255.255.255.0   U     0      0        0 colbr0
192.168.40.0    *               255.255.255.0   U     0      0        0 usrpbr0
192.168.101.0   *               255.255.255.0   U     0      0        0 trbr1
192.168.102.0   *               255.255.255.0   U     0      0        0 trbr2
192.168.103.0   *               255.255.255.0   U     0      0        0 trbr3
192.168.104.0   *               255.255.255.0   U     0      0        0 trbr4
192.168.105.0   *               255.255.255.0   U     0      0        0 trbr5
192.168.106.0   *               255.255.255.0   U     0      0        0 trbr6

calling /root/radio_api/stop.sh on darpa-practice-srn1
return code: 0
stdout: sc2-bot stop/waiting

stderr: 
calling /root/radio_api/stop.sh on darpa-practice-srn2
return code: 0
stdout: sc2-bot stop/waiting

stderr: 
calling /root/radio_api/stop.sh on darpa-practice-srn3
return code: 0
stdout: sc2-bot stop/waiting

stderr: 
calling /root/radio_api/stop.sh on competitor-hurdle-srn4
return code: 255
stdout: 
stderr: 
calling /root/radio_api/stop.sh on competitor-hurdle-srn5
return code: 255
stdout: 
stderr: 
calling /root/radio_api/stop.sh on competitor-hurdle-srn6
return code: 255
stdout: 
stderr: 
running systemctl stop collab_server
Stopping envsim by running ./envsim_control.py stop
Stopping envsim
running systemctl stop envsim

Stopping containers by running ./container_control.py --bot-container-name-base=darpa-practice-srn --competitor-container-name-base=competitor-hurdle-srn --tgen-container-name-base=tgen stop
stoping container tgen1
stoping container tgen2
stoping container tgen3
stoping container tgen4
stoping container tgen5
stoping container tgen6
stoping container darpa-practice-srn1
stoping container darpa-practice-srn2
stoping container darpa-practice-srn3
stoping container competitor-hurdle-srn4
stoping container competitor-hurdle-srn5
stoping container competitor-hurdle-srn6

Pulling traffic log file from tgen1/home/mgen/mgen_traffic_log.drc to ./darpa-practice-srn1_mgen_traffic_log.drc
running lxc file pull tgen1/home/mgen/mgen_traffic_log.drc ./darpa-practice-srn1_mgen_traffic_log.drc
Pulling traffic log file from tgen2/home/mgen/mgen_traffic_log.drc to ./darpa-practice-srn2_mgen_traffic_log.drc
running lxc file pull tgen2/home/mgen/mgen_traffic_log.drc ./darpa-practice-srn2_mgen_traffic_log.drc
Pulling traffic log file from tgen3/home/mgen/mgen_traffic_log.drc to ./darpa-practice-srn3_mgen_traffic_log.drc
running lxc file pull tgen3/home/mgen/mgen_traffic_log.drc ./darpa-practice-srn3_mgen_traffic_log.drc
Pulling traffic log file from tgen4/home/mgen/mgen_traffic_log.drc to ./competitor-hurdle-srn4_mgen_traffic_log.drc
running lxc file pull tgen4/home/mgen/mgen_traffic_log.drc ./competitor-hurdle-srn4_mgen_traffic_log.drc
Pulling traffic log file from tgen5/home/mgen/mgen_traffic_log.drc to ./competitor-hurdle-srn5_mgen_traffic_log.drc
running lxc file pull tgen5/home/mgen/mgen_traffic_log.drc ./competitor-hurdle-srn5_mgen_traffic_log.drc
Pulling traffic log file from tgen6/home/mgen/mgen_traffic_log.drc to ./competitor-hurdle-srn6_mgen_traffic_log.drc
running lxc file pull tgen6/home/mgen/mgen_traffic_log.drc ./competitor-hurdle-srn6_mgen_traffic_log.drc`

**Comment by craig-pomeroy** [comment]
This issue is resolved by the v2-0-0 update.
