### ISSUE TITLE
gr-envsim does not build

### ISSUE THREAD

**Issue by FarshadKoohifar** [SpectrumCollaborationChallenge/phase2-hurdle#6]
When I want to build gr-envsim, I get this:
root@d2:~/gr-envsim/build2# make
Scanning dependencies of target gnuradio-envsim
[  4%] Building CXX object lib/CMakeFiles/gnuradio-envsim.dir/iq_packet.cc.o
[  9%] Building CXX object lib/CMakeFiles/gnuradio-envsim.dir/stream_to_events_impl.cc.o
[ 13%] Building CXX object lib/CMakeFiles/gnuradio-envsim.dir/envsim_source_impl.cc.o
[ 18%] Building CXX object lib/CMakeFiles/gnuradio-envsim.dir/socket_meta_pdu_impl.cc.o
[ 22%] Building CXX object lib/CMakeFiles/gnuradio-envsim.dir/stream_pdu_base.cc.o
[ 27%] Building CXX object lib/CMakeFiles/gnuradio-envsim.dir/env_sink_impl.cc.o
[ 31%] Building CXX object lib/CMakeFiles/gnuradio-envsim.dir/env_block_impl.cc.o
[ 36%] Building CXX object lib/CMakeFiles/gnuradio-envsim.dir/env_source_impl.cc.o
Linking CXX shared library libgnuradio-envsim-1.0.0git.so
[ 36%] Built target gnuradio-envsim
Scanning dependencies of target test-envsim
[ 40%] Building CXX object lib/CMakeFiles/test-envsim.dir/test_envsim.cc.o
[ 45%] Building CXX object lib/CMakeFiles/test-envsim.dir/qa_envsim.cc.o
Linking CXX executable test-envsim
[ 45%] Built target test-envsim
Scanning dependencies of target _envsim_swig_doc_tag
[ 50%] Building CXX object swig/CMakeFiles/_envsim_swig_doc_tag.dir/_envsim_swig_doc_tag.cpp.o
Linking CXX executable _envsim_swig_doc_tag
[ 50%] Built target _envsim_swig_doc_tag
Scanning dependencies of target envsim_swig_swig_doc
[ 54%] Generating doxygen xml for envsim_swig_doc docs
[ 59%] Generating python docstrings for envsim_swig_doc
[ 59%] Built target envsim_swig_swig_doc
Scanning dependencies of target _envsim_swig_swig_tag
[ 63%] Building CXX object swig/CMakeFiles/_envsim_swig_swig_tag.dir/_envsim_swig_swig_tag.cpp.o
Linking CXX executable _envsim_swig_swig_tag
[ 63%] Built target _envsim_swig_swig_tag
[ 68%] Generating envsim_swig.tag
Scanning dependencies of target envsim_swig_swig_2d0df
[ 72%] Building CXX object swig/CMakeFiles/envsim_swig_swig_2d0df.dir/envsim_swig_swig_2d0df.cpp.o
Linking CXX executable envsim_swig_swig_2d0df
Swig source
/usr/local/include/uhd/types/time_spec.hpp:39: Warning 319: No access specifier given for base class 'boost::additive< time_spec_t >' (ignored).
/usr/local/include/uhd/types/time_spec.hpp:39: Warning 319: No access specifier given for base class 'boost::totally_ordered< time_spec_t >' (ignored).
/usr/local/include/uhd/stream.hpp:182: Warning 319: No access specifier given for base class 'boost::noncopyable' (ignored).
/usr/local/include/uhd/stream.hpp:254: Warning 319: No access specifier given for base class 'boost::noncopyable' (ignored).
[ 72%] Built target envsim_swig_swig_2d0df
Scanning dependencies of target _envsim_swig
[ 77%] Building CXX object swig/CMakeFiles/_envsim_swig.dir/envsim_swigPYTHON_wrap.cxx.o
/root/gr-envsim/build2/swig/envsim_swigPYTHON_wrap.cxx: In function ‘PyObject* _wrap_env_source_make(PyObject*, PyObject*, PyObject*)’:
/root/gr-envsim/build2/swig/envsim_swigPYTHON_wrap.cxx:41515:71: error: no matching function for call to ‘gr::envsim::env_source::make(const string&)’
       result = gr::envsim::env_source::make((std::string const &)*arg1);
                                                                       ^
/root/gr-envsim/build2/swig/envsim_swigPYTHON_wrap.cxx:41515:71: note: candidate is:
In file included from /root/gr-envsim/build2/swig/envsim_swigPYTHON_wrap.cxx:4568:0:
/root/gr-envsim/include/envsim/env_source.h:49:15: note: static gr::envsim::env_source::sptr gr::envsim::env_source::make()
   static sptr make();
               ^
/root/gr-envsim/include/envsim/env_source.h:49:15: note:   candidate expects 0 arguments, 1 provided
/root/gr-envsim/build2/swig/envsim_swigPYTHON_wrap.cxx: In function ‘PyObject* _wrap_env_source_sptr_make(PyObject*, PyObject*, PyObject*)’:
/root/gr-envsim/build2/swig/envsim_swigPYTHON_wrap.cxx:41762:56: error: no matching function for call to ‘gr::envsim::env_source::make(const string&)’
       result = (*arg1)->make((std::string const &)*arg2);
                                                        ^
/root/gr-envsim/build2/swig/envsim_swigPYTHON_wrap.cxx:41762:56: note: candidate is:
In file included from /root/gr-envsim/build2/swig/envsim_swigPYTHON_wrap.cxx:4568:0:
/root/gr-envsim/include/envsim/env_source.h:49:15: note: static gr::envsim::env_source::sptr gr::envsim::env_source::make()
   static sptr make();
               ^
/root/gr-envsim/include/envsim/env_source.h:49:15: note:   candidate expects 0 arguments, 1 provided
make[2]: *** [swig/CMakeFiles/_envsim_swig.dir/envsim_swigPYTHON_wrap.cxx.o] Error 1
make[1]: *** [swig/CMakeFiles/_envsim_swig.dir/all] Error 2
make: *** [all] Error 2

**Comment by craig-pomeroy** [comment]
Hi Farshad, 

Were you trying to compile this from inside the competitor base container? 

If it helps, you should be able to start with v2-0-0 of the base container without needing to rebuild gr-envsim as that out of tree module comes preinstalled. 

Can you give the v2-0-0 version of the competitor base container a try and let us know if you are still running into problems?

**Comment by FarshadKoohifar** [comment]
Hi Craig,

I gave the v2-0-0 version of the competitor base container a try. It worked. There remains a minor problem that I am not able to cmake it on a clean slate Xenial with GnuRadio installed:

root@cleanSlate:~/phase2-hurdle/gr-envsim/build# cmake ../
-- Build type not specified: defaulting to release.
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Checking for module 'uhd'
--   No package 'uhd' found
Checking for GNU Radio Module: RUNTIME
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_RUNTIME_FOUND = TRUE
Checking for GNU Radio Module: UHD
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-uhd.so;/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
GNURADIO_UHD_FOUND = TRUE
-- Using install prefix: /usr/local
-- Building for version: v1.0.x-xxx-xunknown / 1.0.0git
-- 
-- Checking for module SWIG
-- Found SWIG version 2.0.12.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
UHD_INCLUDE_DIRS

Fortunately, since this time the base container does have the gnuradio visualization installed, I am not compelled to use a clean slate and building on top of the base is good enough.

Regards,
Farshad

**Comment by craig-pomeroy** [comment]
Hi Farshad,

Glad the new base is working for you. I'll go ahead and close this issue. 

By the way, the CMAKE error you attached points to you not having the Ettus Universal Hardware Driver (UHD) installed. That is a prerequisite for building gr-envsim. If you end up having to go back down that path, see here for how to install UHD: http://files.ettus.com/manual/page_install.html
