### ISSUE TITLE
phase2Hurdle-v2-0-0.tar.gz image has no /share/nas/competitor/images/ directory

### ISSUE THREAD

**Issue by jenelecc** [SpectrumCollaborationChallenge/phase2-hurdle#7]
There is no /share directory (and thus no /share/nas/competitor/images/ ) in the latest phase2Hurdle image - had to create it manually to setup container to run bot configuration and hurdle properly.

**Comment by craig-pomeroy** [comment]
Good catch: We accidentally had that step in our system level test script as opposed to where it should have lived, in the hurdle image generation script. We've updated the image generator and that directory will be included in all subsequent builds. I'll close this after the next point release.

**Comment by craig-pomeroy** [comment]
The most recent image uploads now include this directory.
