### ISSUE TITLE
traffic scoring (or packet rate initialization) error

### ISSUE THREAD

**Issue by jenelecc** [SpectrumCollaborationChallenge/phase2-hurdle#8]
The traffic scoring calculation assumes that the bots and competitors have the same packet rate:
https://github.com/SpectrumCollaborationChallenge/phase2-hurdle/blob/v2-0-0/hurdle_execution/traffic_scoring.py#L62

This is not the case as the rate passed into traffic control is only for the bots and not the competitor:
https://github.com/SpectrumCollaborationChallenge/phase2-hurdle/blob/v2-0-0/hurdle_execution/run_hurdle.py#L453

https://github.com/SpectrumCollaborationChallenge/phase2-hurdle/blob/v2-0-0/hurdle_execution/traffic_control.py#L225
https://github.com/SpectrumCollaborationChallenge/phase2-hurdle/blob/v2-0-0/hurdle_execution/traffic_control.py#L232
https://github.com/SpectrumCollaborationChallenge/phase2-hurdle/blob/v2-0-0/hurdle_execution/traffic_control.py#L291

Bots are passed a rate of 15 whereas competitors use their default of 10.

I have verified this is the case by looking at /home/mgen/mgen_traffic.mgn on tgen1-6.  tgen1-3 show:
# MGEN SCRIPT tgen3_traffic.mgn
0.0 ON 1 UDP SRC 5001 DST 192.168.101.2/5003 PERIODIC [15.0 200]
0.0 ON 2 UDP SRC 5002 DST 192.168.102.2/5003 PERIODIC [15.0 200]

whereas tgen4-6 show:
# MGEN SCRIPT tgen5_traffic.mgn
0.0 ON 1 UDP SRC 5004 DST 192.168.104.2/5005 PERIODIC [10.0 200]
0.0 ON 2 UDP SRC 5006 DST 192.168.106.2/5005 PERIODIC [10.0 200]

**Comment by craig-pomeroy** [comment]
You are absolutely correct. The packet rate parameter from run_hurdle.py should be passed to both comp-peak-msg-rate and bot-peak-msg-rate in traffic_control.py. Testing the fix now.

**Comment by jenelecc** [comment]
awesome - thanks
